name: FC Mobile Code Alert

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python packages
        run: |
    python -m pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
